version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: storyforge_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-runner
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/storyforge_db?schema=public
      JWT_SECRET: your_jwt_secret_key # REPLACE WITH A STRONG SECRET
      OPENAI_API_KEY: your_openai_api_key # REPLACE WITH YOUR KEY
      ANTHROPIC_API_KEY: your_anthropic_api_key # REPLACE WITH YOUR KEY
    depends_on:
      - db
    command: bash -c "npm run migrate:up && npm run start:prod"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-runner
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://api:3000/api
      NEXT_PUBLIC_WS_URL: ws://api:3000
    depends_on:
      - api

volumes:
  pg_data:
